### PR TITLE
Feature/253

### PR DESCRIPTION
**Pull request by SinyukKirill**
Includes #248

### CODE REVIEW

**Comment by josdem** [comment]
Great job @SinyukKirill clean code, and all tests are passing: https://ci.josdem.io/job/vetlog/61/
@marki2121 As you can see an open PR triggered the Jenkins job 🎉

**Review by josdem — APPROVED** [review]

**Comment by marki2121** [comment]
@josdem Yes i can see it

**Comment by josdem** [comment]
> @josdem Yes i can see it 

I will write a technical post next week and I will share it with you

**Comment by josdem** [comment]
@all-contributors please add @kirillsinyuk for code

**Pull request merged**
