### PR TITLE
feature-348:Adding Regiser to header for new user

### PR DESCRIPTION
**Pull request by Irfan0025**

### CODE REVIEW

**Review by josdem — CHANGES_REQUESTED** [review]
Hi @Irfan0025  thank you for sending this PR, we need some changes here:
- Since the register option is for a pet, the message should be `Register a Pet` therefore you need this message properties: https://github.com/josdem/vetlog-spring-boot/blob/main/src/main/resources/i18n/messages.properties#L92L94
- This menu option should appear in authenticated users, therefore please add it to the div section: `<div sec:authorize="isAuthenticated()">`  as well.

**Review by josdem — APPROVED** [review]
Now looks good to me, thanks.

**Comment by josdem** [comment]
@all-contributors please add @Irfan0025 for code

**Comment by kaminuma** [comment]
Hi @Irfan0025 @josdem 

> Since the register option is for a pet, the message should be Register a Pet therefore you need this message properties: https://github.com/josdem/vetlog-spring-boot/blob/main/src/main/resources/i18n/messages.properties#L92L94
> This menu option should appear in authenticated users, therefore please add it to the div section: `<div sec:authorize="isAuthenticated()">` as well.


It looks like the above two changes are not included in the file changes on my github page, what do you think?

**Review by kaminuma — CHANGES_REQUESTED** [review]
Hi @Irfan0025 @josdem 

- > This menu option should appear in authenticated users, therefore please add it to the div section:` <div sec:authorize="isAuthenticated()">` as well.

It looks like the above  changes are not included in the file changes on my github page, what do you think?

**Comment by josdem** [comment]
> Hi @Irfan0025 @josdem
> 
> * > This menu option should appear in authenticated users, therefore please add it to the div section:` <div sec:authorize="isAuthenticated()">` as well.
> 
> It looks like the above changes are not included in the file changes on my github page, what do you think?

Hi @kaminuma what do you mean with Github page?

**Comment by kaminuma** [comment]
> > Hi @Irfan0025 @josdem
> > 
> > * > This menu option should appear in authenticated users, therefore please add it to the div section:` <div sec:authorize="isAuthenticated()">` as well.
> > 
Hi @josdem 
Are the above changes included this PR?

**Comment by josdem** [comment]
> > > Hi @Irfan0025 @josdem
> > > 
> > > * > This menu option should appear in authenticated users, therefore please add it to the div section:` <div sec:authorize="isAuthenticated()">` as well.
> 
> Hi @josdem Are the above changes included this PR?

Yes, the acceptance criteria is to add a `Register a pet` option in the main menu, this functionality should work for guest and authenticated users, and seems to me that those changes are set here:

menu_changes

**Review by kaminuma — APPROVED** [review]
@Irfan0025 @josdem 
I'm sorry.
I cut the branch again and checked, and was able to find the above statement.
Approved

**Pull request merged**
