### PR TITLE
Wrong message on account created/332

### PR DESCRIPTION
**Pull request by Prathyusha287**
###Description :
This pull request resolves issue #332.
In the URL [http://localhost:8080/user/create](https://github.com/josdem/vetlog-spring-boot/compare/main...Prathyusha287:vetlog-spring-boot:features/url), after filling in the fields with valid information and clicking the submit button, the expected message should be "Your account is created." However, it currently displays "An email was sent with recovery instructions." 

###What does this implement/fix ?
This fix modifies the behavior after the user submits valid information when creating an account. Instead of showing an incorrect message, the system will now display an alert message that reads:
"Your account was created, but you need to activate it. Please check your email."
This ensures that users receive accurate feedback when their account is successfully created and that they are informed about the email verification process.

###Additional context:
This fix applies to the login.html file in resources/templates/login/.
A new div was added to show the success message for user account creation. 
Also renamed   'message' as  'userAccountCreatedMessage'  in save method in Usercontroller.

### CODE REVIEW

**Comment by Prathyusha287** [comment]
* A new <div> was added to show the success message for user account creation in login.html

**Review by josdem — APPROVED** [review]
Looks good to me, thank you for the fix @Prathyusha287

**Comment by josdem** [comment]
@all-collaborators please add @Prathyusha287 for code

**Comment by josdem** [comment]
@all-contributors please add @Prathyusha287 for code

**Comment by kaminuma** [comment]
@Prathyusha287
Checked and everything is working as expected.
However, the wording of the message seems to be different from the one written in the issues #332 .
The nuances are the same and we don't think there will be any impact on user operations, 

@josdem
Please double check that there are no problems with the wording.
スクリーンショット 2024-09-14 215547

**Comment by josdem** [comment]
> @Prathyusha287 Checked and everything is working as expected. However, the wording of the message seems to be different from the one written in the issues #332 . The nuances are the same and we don't think there will be any impact on user operations,
> 
> @josdem Please double check that there are no problems with the wording. スクリーンショット 2024-09-14 215547

Good catch @kaminuma!
@Prathyusha287 please modify the internationalization files in order to match with expected result.
1. https://github.com/josdem/vetlog-spring-boot/blob/main/src/main/resources/i18n/messages.properties#L69-L71 ("Your account was created".)
2. https://github.com/josdem/vetlog-spring-boot/blob/main/src/main/resources/i18n/messages_es.properties#L72-L74 ("Tu cuenta fue creada")

**Review by josdem — CHANGES_REQUESTED** [review]
@Prathyusha287  a small change to improve this PR is necessary. Let me know if any questions.

**Comment by Prathyusha287** [comment]
Hi @josdem  I made those changes and pushed it to the branch . Is there anything to be done?

**Review by josdem — APPROVED** [review]
Thank you for doing suggested changes! 👍

**Comment by Prathyusha287** [comment]
Hi @josdem  is it Tú cuenta fue creada or Tu cuenta fue creada ? If it's the first one i will change it.

**Comment by josdem** [comment]
> Thank you for doing suggested changes! 👍

@kaminuma please your approval when you have a chance.

**Comment by josdem** [comment]
> Hi @josdem is it Tú cuenta fue creada or Tu cuenta fue creada ? If it's the first one i will change it.

"Tu cuenta fue creada" is correct, no worries.

**Review by kaminuma — APPROVED** [review]
[LGTM]

**Pull request merged**
