### PR TITLE
[medium]Feature/344

### PR DESCRIPTION
**Pull request by josdem**
- Setting vaccines as select / option fields
- Updating vaccination status date
- Adding vaccination list field to the tests
- Setting up release version 🎉

**Screenshot**
edit_pet_with_vaccines

### CODE REVIEW

**Review by kaminuma — APPROVED** [review]
Hi @josdem 
I was a little concerned about the height of the select box,
but there were no problems with its operation.

I would like to approve

**Comment by josdem** [comment]
> Hi @josdem I was a little concerned about the height of the select box, but there were no problems with its operation.
> 
> I would like to approve

Agreed; however, I have to confess that I am not good at the front-end, you are welcome if you can do a little improvement in the drop-down menu size.

**Comment by kaminuma** [comment]
@josdem 

I tried matching the select box to the existing height by directly writing it in style 
(I don't know where to write it in the CSS file)
For now, I will report this as a layout correction.

スクリーンショット 2024-10-04 221744


I can push the modified version immediately, but what should I do?

**Comment by josdem** [comment]
> Hi @josdem
> 
> I tried matching the select box to the existing height by directly writing it in style (I don't know where to write it in the CSS file) For now, I will report this as a layout correction.
> 
> スクリーンショット 2024-10-04 221744
> 
> I can push the modified version immediately, but what should I do?

No worries, you did it right, we normally create a PR with a small change. 
Optionally, and following conventions, you can name the branch as `hotFix/add-a-description`

**Pull request merged**
