### PR TITLE
Fix Birthdate Format on Adoption Page

### PR DESCRIPTION
**Pull request by AviraLS22**
*** Description
This PR addresses the issue of birthdate formatting on the pet adoption page. Previously, the birthdate was displayed in the format `YYYY-MM-ddTHH:MM`, which was not user-friendly. 

***Changes Made:
- Updated the Thymeleaf template to format the birthdate as `MM-dd-yyyy` using Thymeleaf's built-in date formatting capabilities.
- Ensured that the display is more intuitive for users, enhancing the overall user experience.

***Context for Reviewers:
These changes improve the clarity and readability of the pet's birthdate information for potential adopters, aligning with common date formatting standards. 

***Issue Addressed:
This change is related to issue #345

### CODE REVIEW

**Review by josdem — CHANGES_REQUESTED** [review]
Hi @AviraLS22 , thank you for submit a PR.
- It is working this  Thymeleaf's built-in date formatting? because I am getting this error:
```EL1004E: Method call: Method format(java.time.LocalDateTime,java.lang.String) cannot be found on type org.thymeleaf.expression.Dates```
- You can use a bean we have to format dates, please take a look at the `pet/list.html` template:
` <li th:text="${@dateFormatter.formatToDate(pet.birthDate, #locale)}"/>`
- Seems like you need to pull changes from main, because `user/create.html` template already has the required country code drop-down menu.

https://github.com/josdem/vetlog-spring-boot/blob/main/src/main/resources/templates/user/create.html#L68-L122

**Comment by AviraLS22** [comment]
Hi  @josdem ,

Thank you for your feedback! I will replace the date formatting with the custom `dateFormatter` bean as suggested. Additionally, I'll pull the latest changes from the `main` branch to incorporate the country code drop-down menu.

I appreciate your guidance, and I'll update the PR shortly.

Best,  
AviraLS22

**Comment by AviraLS22** [comment]
Hi @josdem ,

Thank you for your feedback! I’ve updated the code to use the custom date formatter as suggested. The line for formatting the birth date now utilizes the dateFormatter bean.

Please let me know if there are any further changes needed or if everything looks good!

Best,
@AviraLS22

**Comment by josdem** [comment]
> Hi @josdem ,
> 
> Thank you for your feedback! I’ve updated the code to use the custom date formatter as suggested. The line for formatting the birth date now utilizes the dateFormatter bean.
> 
> Please let me know if there are any further changes needed or if everything looks good!
> 
> Best, @AviraLS22

Thanks @AviraLS22 , did you push your changes?

**Comment by AviraLS22** [comment]
@josdem  yes sir i have pushed it .

**Comment by josdem** [comment]
We will integrate this changes in the PR https://github.com/josdem/vetlog-spring-boot/pull/354 ; therefore I will close this PR.

**Comment by AviraLS22** [comment]
Thanks for the update, @josdem ! I appreciate the integration of my changes into PR #354.

**Pull request closed without merging**
