### PR TITLE
[small]feature/305

### PR DESCRIPTION
**Pull request by josdem**
- Adding vaccination repository
- Adding vaccination service
- Adding logic to schedule vaccinations based on how old it is the dog, following this program: https://github.com/josdem/vetlog-spring-boot/wiki/Vaccination-Program
- Adding required tests to cover functionality

### CODE REVIEW

**Comment by josdem** [comment]
> ## [Quality Gate Passed](https://sonarcloud.io/dashboard?id=josdem_vetlog-spring-boot&pullRequest=340) **Quality Gate passed**
> Issues  [3 New issues](https://sonarcloud.io/project/issues?id=josdem_vetlog-spring-boot&pullRequest=340&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true)  [0 Accepted issues](https://sonarcloud.io/project/issues?id=josdem_vetlog-spring-boot&pullRequest=340&issueStatuses=ACCEPTED)
> 
> Measures  [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=josdem_vetlog-spring-boot&pullRequest=340&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true)  [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=josdem_vetlog-spring-boot&pullRequest=340&metric=new_coverage&view=list)  [0.0% Duplication on New Code](https://sonarcloud.io/component_measures?id=josdem_vetlog-spring-boot&pullRequest=340&metric=new_duplicated_lines_density&view=list)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=josdem_vetlog-spring-boot&pullRequest=340)

Working on solving reported SonarCloud isues 🥴

**Comment by kaminuma** [comment]
Hi @josdem 
I would like to review this PR, but when registering a pet locally, an error occurs when uploading images. Is there anything I need to do to register my pet locally?

**Comment by josdem** [comment]
> Hi @josdem I would like to review this PR, but when registering a pet locally, an error occurs when uploading images. Is there anything I need to do to register my pet locally?

Hi @kaminuma thank you for review the PR. The error happening when an user is trying to register a pet in their local is expected, the reason is due to we need credentials aka `vetlog.json` file to upload images to the cloud. To avoid this error, just create a pet witout image.

**Comment by kaminuma** [comment]
@josdem 
I see!
understood.
thanks 
Check the code additions and corrections

**Review by kaminuma — APPROVED** [review]
`import java.time.temporal.ChronoUnit;`
I can't read it, but as a result of my investigation, it seems to be a problem in my local environment. 

I checked the code and I think there is no problem.

**Comment by josdem** [comment]
> `import java.time.temporal.ChronoUnit;` I can't read it, but as a result of my investigation, it seems to be a problem in my local environment.
> 
> I checked the code and I think there is no problem.

That is a weird error, since `ChronoUnit` is available since Java 8 and under JDK package `java.base` JAR, based on that I recommend this troubleshooting:

- Using IntelliJ: Try to change / update  JDK at File > Project structure > Project SDK
- Try to run this project in another IDE like Eclipse.

I hope this helps.

**Comment by josdem** [comment]
> > `import java.time.temporal.ChronoUnit;` I can't read it, but as a result of my investigation, it seems to be a problem in my local environment.
> > I checked the code and I think there is no problem.
> 
> That is a weird error, since `ChronoUnit` is available since Java 8 and under JDK package `java.base` JAR, based on that I recommend this troubleshooting:
> 
> * Using IntelliJ: Try to change / update  JDK at File > Project structure > Project SDK
> * Try to run this project in another IDE like Eclipse.
> 
> I hope this helps.

@kaminuma I was able to reproduce the issue, try to change to Java SDK 17
Screenshot from 2024-09-20 08-19-56

**Comment by josdem** [comment]
> > > `import java.time.temporal.ChronoUnit;` I can't read it, but as a result of my investigation, it seems to be a problem in my local environment.
> > > I checked the code and I think there is no problem.
> > 
> > 
> > That is a weird error, since `ChronoUnit` is available since Java 8 and under JDK package `java.base` JAR, based on that I recommend this troubleshooting:
> > 
> > * Using IntelliJ: Try to change / update  JDK at File > Project structure > Project SDK
> > * Try to run this project in another IDE like Eclipse.
> > 
> > I hope this helps.
> 
> @kaminuma I was able to reproduce the issue, try to change to Java SDK 17 Screenshot from 2024-09-20 08-19-56

And or update Intellij to `2023.1` version or above, more information here: https://youtrack.jetbrains.com/issue/IDEA-333976/Some-java-classes-in-OpenJDK-21-are-not-accessible

**Comment by kaminuma** [comment]
amazing!
thank you @josdem 

By changing to Java17, ChronoUnit was successfully loaded.
It was helpful because I was having trouble, not because the SDK version was old.

スクリーンショット 2024-09-20 214624

スクリーンショット 2024-09-20 214528

**Pull request merged**
