### PR TITLE
Updating Version

### PR DESCRIPTION
**Pull request by trustbycode**
Dependencies Update:
Spring Boot
Thymeleaf Security5
Mockito

awsLambdaVersion = '1.1.0'
awsJavaVersion = '1.11.98'

Needs an update if you're migrating to Java v2

### CODE REVIEW

**Comment by josdem** [comment]
Hi @trustbycode thanks for sending a PR to the project. I do not think these changes are enough to update the Spring Boot version since 3.0 uses the Servlet 6.0 and JPA 3.1 specifications. here is more information about it: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#Jakarta-EE

**Comment by trustbycode** [comment]
Okay. Will check through that also Did you check on the update for the deprecated WebSecurityConfigurerAdapter which I made changes on my to SecurityFilterChain in your Security Config class ?

**Comment by josdem** [comment]
Hi @trustbycode, please take a look at this PR draft; almost all required changes are done, we are getting an error from the Google Spring Cloud library. I hope this information helps. https://github.com/josdem/vetlog-spring-boot/pull/212

**Comment by trustbycode** [comment]
I just got notified about your changes and I can boldly say changes I made was inline with the documentation and I checked on the issue I see it exactly the bug I solved you replace without accepting my pull request for both the dependencies and web security. It’s all good and best wishes

**Comment by josdem** [comment]
Sorry, I can not merge code that is not passing tests or even compiling.

**Comment by trustbycode** [comment]
It is on my end and it exactly the same code that is reflecting on the changes but never mind 😁 @josdem  Best wishes and regards

**Pull request closed without merging**
